#!/bin/bash
### NAME
###     py-test-all - test all python files
###

set -eu
PY_SOURCES=*.py
if which pytest-2 &>/dev/null; then
    PYTEST=pytest-2
elif which py.test-2.7 &>/dev/null; then
    PYTEST=py.test-2.7
else
    echo "pytest-2 is not installed" > /dev/stderr
    exit 1
fi

## pytest
echo "====== pytest-2 ======" > /dev/stderr
$PYTEST  *.py

## Pylint
echo "====== pylint ======" > /dev/stderr
python2 -m pylint $PY_SOURCES

## flake8
echo "====== flake8 =====" > /dev/stderr
## E126(continuation line over-indented for hanging indent) seems to
## clash with pylint indent rules
flake8 --ignore E126 --benchmark $PY_SOURCES


