#!/bin/bash -eu
### NAME
###     zanata-version-update - Update the Zanata dependencies
###
### SYNOPSIS
###     zanata-version-update [Option] [<module>|<artifact>]
###
### DESCRIPTION
###     This program updates pom.xml to use latest release
### of the dependencies in org.zanata
###
### ARGUMENTS
###     <module>: module name like zanata-platform
###
###     <artifact>: artifact like platform
###
###     <branch>: branch to work on. By default it is releasing branch.
###
### OPTIONS
###     -h: Show help.
###
###     -B: Batch mode
###         It will NOT ask question and proceed with default choice.
###
###     -j: Jenkins mode.
###         This assumes that current directory is <module> work directory.
###         and correct branch is checked out.
###
###     -n: Allow Snapshots
###
###     -p: Push after commit
###         Git push when it has commit.
###
### ENVIRONMENT_VARIABLES
###     EXCLUDE_PROPERTIES: A comma separated list of properties to not update.
: ${EXCLUDE_PROPERTIES:=zanata.api.compat.version}

VERSIONS_PLUGIN="org.codehaus.mojo:versions-maven-plugin:2.3"

###
shopt -s globstar
ScriptDir=$(dirname $(readlink  -q -f $0))
FunctionScriptFile=${ScriptDir}/zanata-functions
source "${FunctionScriptFile}"
trap exit_print_error EXIT
ProgramName=$(basename $0)


##=== parsing Start ===
print_status -t "parse" -s "Start"
BatchMode=0
JenkinsMode=0
PushMode=0
AllowSnapshot=0
VersionGoal=use-latest-releases
declare -a ExtraOptionArray=()

while getopts "hBjnp" opt;do
    case $opt in
	h )
	    zanata_script_help $0
	    exit ${EXIT_OK}
	    ;;
	B )
	    BatchMode=1
	    ;;
	j )
	    JenkinsMode=1
	    ;;
	n )
	    AllowSnapshot=1
	    VersionGoal=use-next-versions
	    ExtraOptionArray+=(-DallowSnapshots=true)
	    ;;
	p )
	    PushMode=1
	    ;;
	* )
	    failed ${EXIT_FATAL_INVALID_OPTIONS} "$opt"
	    ;;
    esac
done
export JenkinsMode
shift $((OPTIND-1))

## Get Module
branch_prepare RELEASING "$@"
shift $ShiftOffset
print_status " Module=$Module"

##=== update Start ===
print_status -t update  -s "Start"

CmdOptArray=( ${VERSIONS_PLUGIN}:update-parent ${ExtraOptionArray[@]-})
print_status " ${CmdOptArray[*]}"
mvn "${CmdOptArray[@]}"

CmdOptArray=( ${VERSIONS_PLUGIN}:$VersionGoal '-Dincludes=org.zanata:*' ${ExtraOptionArray[@]-} )
print_status " ${CmdOptArray[*]}"
mvn "${CmdOptArray[@]}"

CmdOptArray=( ${VERSIONS_PLUGIN}:update-properties '-Dincludes=org.zanata:*' '-DincludeProperties=zanata.assets.version' '-DexcludeProperties=${EXCLUDE_PROPERTIES}' ${ExtraOptionArray[@]-} )
set -x
mvn "${CmdOptArray[@]}"
set +x

if ! git diff --exit-code ;then
    if [ $BatchMode -eq 0 ];then
	read -p "### Are the change looks alright? Press [Ctrl-C] to break, [Enter] to continue"
    fi
    git commit -a -m "chore(version): Update Zanata dependencies"
    if [ $PushMode -ge 1 ];then
	git push
    else
	exit ${EXIT_RETURN_FALSE}
    fi
else
    print_status " No change detected"
fi
exit ${EXIT_OK}

