#!/bin/bash -eu
### NAME
###     zanata-artifact-m2repo - Get artifact list from m2 repo
###
### SYNOPSIS
###     zanata-artifact-m2repo [options] <dir>
###     zanata-artifact-m2repo -l
###     zanata-artifact-m2repo -t
###
### DESCRIPTION
###     This program produces artifact list from m2 repo
###
ScriptDir=$(dirname $(readlink  -q -f $0))
FunctionScriptFile=${ScriptDir}/zanata-functions
source "$FunctionScriptFile"
trap exit_print_error EXIT

##=== parsing Start ===
print_status -t parsing -s "Start"
M2Repo=

###
### OPTIONS
while getopts "hlt" opt;do
    case $opt in
###
###     -h: Show this help
	h )
	    zanata_script_help $0
	    exit $EXIT_OK
	    ;;
###
###     -l: Use maven default m2 repository directory, i.e.
###        $HOME/.m2/repository
        l )
            M2Repo=$HOME/.m2/repository
	    ;;
###
###     -t: Use repository dir dump from zanata-maven-release
###         zanata-maven-release will download the artifacts
###         to $REPO_LOCAL_DIR, by default, it is
###         /tmp/zanata/maven-central-release-repo
        t )
            M2Repo=$REPO_LOCAL_DIR
	    ;;
	* )
            failed $EXIT_FATAL_INVALID_OPTIONS "$opt"
            ;;
    esac
done
shift $((OPTIND-1))
[[ -z $M2Repo ]] && failed $EXIT_FATAL_INVALID_OPTIONS "Please either specify m2 directory, or use option -l or -t"

[[ ! -r $M2Repo ]] && failed $EXIT_FATAL_MISSING_DEPENDENCY "Directory $M2Repo is not readable"

find $M2Repo -name '*.pom' -printf '%h\n' | sed -e 's|^'$M2Repo/'||' \
    | sed -e 's|\(.*\)/\([^/]*\)|\1:\2|' | sed -e 's|\(.*\)/\([^/]*\)|\1:\2|' \
    | sed -s 's|/|.|g'
