#!/bin/bash
### NAME
###     zanata-nexus - Release maven artifacts in nexus-staging
###     via nexus-staging-maven-plugin
###
### SYNOPSIS
###     zanata-nexus [options] [Projects]
###
### DESCRIPTION
###     This script is currently not used because 
###     org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy is not a drop-in
###     replacement. It generate following error
###    [ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (default-cli) on project build-tools:
###     The packaging for this project did not assign a file to the build artifact.
###
###     This script deploy to nexus staging, close it, and release from it.
###
###     Note that this script assume you are already in correct directory and
###     checkout correct branch.
###
###     plugin docs:
###         https://github.com/sonatype/nexus-maven-plugins/tree/master/staging/maven-plugin
###
### ENVIRONMENT
###     ZANATA_RELEASE_MODE:
###         <empty>  : Default mode. Builds, deploy to nexus staging, and push changes
###                to source control
###         testBuild: Builds,  deploy to nexus staging, but does not push changes to
###                source control, and nor does it close the nexus staging repo
###         dryRun   : Only show command to be run.
: ${ZANATA_RELEASE_MODE:=}
: ${DryRunMode:=0}

export LC_ALL=C
set -eu
ScriptDir=$(dirname $(readlink  -q -f $0))
FunctionScriptFile=${ScriptDir}/zanata-functions
source "$FunctionScriptFile"
trap exit_print_error EXIT

###
### OPTIONS
while getopts "h" opt;do
    case $opt in
###     -h: Show detail help
        h )
            zanata_script_help $0
            exit ${EXIT_OK}
            ;;
        * )
            failed ${EXIT_FATAL_INVALID_OPTIONS} "$opt"
            ;;
    esac
done
shift $((OPTIND-1))

PluginFlags="-DautoReleaseAfterClose=true"
case $ZANATA_RELEASE_MODE in
    dryRun )
        DryRunMode=1
        ;;
    testBuild )
        DryRunMode=0
        PluginFlags="-DautoReleaseAfterClose=false -DskipStagingRepositoryClose=true"
        ;;
    * )
        ;;
esac
export DryRunMode

Projects="${1-}"


if [[ -n $Projects && $Projects != 'null' ]]; then
    ProjectOpts="-pl $Projects"
else
    ProjectOpts=""
fi

## Assumption: Staging repository state is CLOSED here
## If not we have to load nexus-staging-maven-plugin:rc-list again,
## which might take 1 or 2 minutes to complete.
print_status " nexus:deploy"


if [[ $ZANATA_RELEASE_MODE = testBuild ]]; then
    export DryRunMode=1
fi
run_command ./mvnw $MAVEN_NEXUS_STAGING_OPTIONS ${MAVEN_NEXUS_STAGING_PLUGIN}:deploy \
    -DprofileId=org.zanata  ${ProjectOpts}

## No need to restore DryRunMode in end of the script

