#!/bin/bash

set -e

function print_usage(){
    cat <<-END
SYNOPSIS
    zanata-nexus-staging [options] <PROJECT>
    zanata-nexus-staging-tennera   [options]
    zanata-nexus-staging-openprops [options]
    zanata-nexus-staging-parent    [options]
    zanata-nexus-staging-api       [options]
    zanata-nexus-staging-common    [options]
    zanata-nexus-staging-client    [options]

OPTIONS
    -h: Show this help
    -b: Big release.
        Integration/master need to be updated.
        (e.g. when releasing from 3.7.X -> 3.8.0).
        If not specified, only the default branch will be touch
        (e.g. when releasing from 3.7.0 -> 3.7.1 ).
	Default branch is:
	  release if it has release; otherwise
	  integration/master if it has release; otherwise
	  master.

    -r: Skip release plugin

DESCRIPTION
    This program perform the release and push the relese with nexus.
It can do following tasks:

 * For making a X release (e.g. 3.Y.Z -> 4.0.0) or 
   Y release: (e.g. 3.7.Z -> 3.8.0 ), run:

   zanata-nexus-staging-<module> -b

 * For making a Z release (e.g. 3.7.0 -> 3.7.1 ), run 

   zanata-nexus-staging-<module>

 * If tag is made but release failed, and you fixed it without changing 
   the source, You can resume the release process with 
  
   zanata-nexus-staging-<module> -r


ENVIRONMENT
    DEFAULT_BRANCH
      Branch is automatically determined by PROJECT.
      Specify Environment DEFAULT_BRANCH to override.
	
    WORK_ROOT
      The base directory for repository checkout
      As maven release plugin generally require a clean git working tree
      This script will clean it for you.
      Thus it is better not use normal working directory.
	
    REPO_LOCAL_DIR (Optional)
      The directory for maven repo
      This should NOT be your normal work maven repo
	
EXIT_STATUS
    EXIT_INVALID_OPTIONS=3
    EXIT_FAIL_TO_CLONE=4
    EXIT_RELEASE_GOAL_FAIL=5
END
}

function echo_stderr(){
    echo "$1" > /dev/stderr
}

function ensure_repo(){
    echo "### Ensure the repo $prj is at ${WORK_ROOT}/${prj}"
    local prj=$1
    local git_repo_url="git@github.com:zanata/${prj}.git"
    pushd ${WORK_ROOT}
    if [ ! -d ${prj} ];then
        git clone ${git_repo_url}
        if [ $? -ne 0 ];then
	    echo_stderr "[ERROR] Failed to clone ${git_repo_url}"
	    exit ${EXIT_FAIL_TO_CLONE}
       fi
    fi
    popd
}

function does_branch_exist(){
    local prj=$1
    local branch=$2
    echo -n "### Does ${prj} has branch ${branch}?..."
    if git rev-parse --verify ${branch} &>/dev/null;then
        echo "yes" 
        return 0
    else
        echo "no"
        return 1 
    fi
}

: ${WORK_ROOT:=/tmp/zanata}
: ${REPO_LOCAL_DIR:=/tmp/maven-central-release-repo}

EXIT_INVALID_OPTIONS=3
EXIT_FAIL_TO_CLONE=4
EXIT_RELEASE_GOAL_FAIL=5

BIG_RELEASE=
SKIP_RELEASE_PLUGIN=

while getopts "brh" opt;do
    case $opt in
	h )
	    pring_usage
	    exit 0
	    ;;
        b )
	    BIG_RELEASE=1
	    ;;
	r )
	    SKIP_RELEASE_PLUGIN=1
	    ;;
	* )
	    echo "Invalid option $opt" > /dev/stderr
	    exit ${EXIT_INVALID_OPTIONS}
	    ;;
    esac
done

shift $((OPTIND-1))
if [ -n "$1" ];then
    PROJECT="$1"
fi

case $0 in
    *-tennera)
	PROJECT=tennera
        ;;
    *-openprops)
	PROJECT=openprops
	;;
    *-parent)
	PROJECT=zanata-parent
	;;
    *-api)
	PROJECT=zanata-api
	;;
    *-common)
	PROJECT=zanata-common
	;;
    *-client)
	PROJECT=zanata-client
	;;
    *)
	if [ -z "$PROJECT" ]; then
	    print_usage
	    exit ${EXIT_INVALID_OPTIONS}
	fi
	;;
esac

### Set default branches
if [ -z "${DEFAULT_BRANCH}" ];then
    case ${PROJECT} in
        tennera | openprops )
	    DEFAULT_BRANCH=master
            ;;
        zanata-parent )
	    DEFAULT_BRANCH=integration/master
            ;;
        zanata-api | zanata-common | zanata-client)
	    DEFAULT_BRANCH=release
            ;;
    esac
fi
echo "### Releasing $PROJECT in branch ${DEFAULT_BRANCH}" 

if [ ! -d ${WORK_ROOT} ];then
    mkdir -p ${WORK_ROOT}
fi

ensure_repo ${PROJECT}

cd ${WORK_ROOT}/${PROJECT}
git fetch

HAS_RELEASE_BRANCH=
does_branch_exist ${PROJECT} origin/release && HAS_RELEASE_BRANCH=1

HAS_INTEGRATION_MASTER_BRANCH=
does_branch_exist ${PROJECT} origin/integration/master && 
HAS_INTEGRATION_MASTER_BRANCH=1

### Update existing release branch
echo "### Pre-release: update existing release branchs"
if [ -n "$HAS_RELEASE_BRANCH" ];then
    git checkout release

    echo "### [pre-release] Branch release: merge origin/release"
    git merge origin/release --ff-only --quiet
    if [ -n "${BIG_RELEASE}" ];then
        echo "### [pre-release] Branch release: merge origin/master as we do the big release"
        git merge origin/master --ff-only --quiet
    fi
    echo "### [pre-release] Branch release: updated"
    git push origin release
fi

### Update existing integration/master branch on BIG_RELEASE
echo "### Pre-release: update existing integration/master branchs"
if [ -n "${BIG_RELEASE}" -a -n "$HAS_INTEGRATION_MASTER_BRANCH" ];then
    git checkout integration/master

    echo "### [pre-release] Branch integration/master merge origin/integration/master"
    git merge origin/integration/master --ff-only --quiet

    echo "### [pre-release] Branch integration/master: Create new version"
    mvn -e release:update-versions -DautoVersionSubmodules=true

    git commit pom.xml */pom.xml -m "prepare for next development iteration"
    git push origin integration/master
    echo "### [pre-release] integration/master branch updated"
fi

### Release process
function release_perform(){
    if [ -z "${SKIP_RELEASE_PLUGIN}" ];then
        git clean -f -d
        if [ "$PROJECT" != "zanata-parent" ];then
             ensure_repo zanata-parent
        fi
        
        echo "### [release_perform] Start"
        mvn -e -Dmaven.repo.local=$REPO_LOCAL_DIR -Dgpg.useagent release:clean release:prepare release:perform
        if [ $? -ne 0 ];then
	    echo_stderr "### [ERROR]: release goals failed"
	    exit ${EXIT_RELEASE_GOAL_FAIL}
        fi
    fi
    echo "### [release_perform] Done"
    return 0
}

echo "### [release] Start"
git checkout ${DEFAULT_BRANCH}
git fetch --tags
git pull

case $PROJECT in
    zanata-parent | zanata-api | zanata-common )
	### zanata-parent has only master
	release_perform

        echo "### [release] nexus-staging:release"
	mvn -e nexus-staging:release -Psonatype-oss-release \
	    -DstagingRepositoryId=$(grep -oP '^stagingRepository\.id=\K.*' target/checkout/target/nexus-staging/staging/*.properties)
	;;
    zanata-client )
	### auto nexus-staging does not seem to work with zanata-client
	### Need to use manual bundle jars
	release_perform

        ### Create and sign the artifacts
        echo "### [release] Create and sign the artifacts"
	mvn -e clean deploy source:jar javadoc:jar jar:jar gpg:sign -Dgpg.useagent -DskipTests=true -DskipArqTests=true -Dfindbugs.skip=true 

	### make bundles for each submodules:
	SUBMODULES=(. zanata-cli zanata-client-commands zanata-maven-plugin zanata-rest-client)
	BUNDLE_JARS=()
	for sm in "${SUBMODULES[@]}"; do
	    pushd ${sm}/target
	    jar cvf bundle.jar $(for i in `LANG=C find . -name  "*.asc" | sed -e 's/.asc$//' | xargs`;do echo -n $i $i.asc " ";done)
	    BUNDLE_JARS+="${sm}/target/bundle.jar"
	    popd
	done

	### Notify user to upload bundles
	cat <<-END
	Please:
	1. Login to oss.sonatype.org
	2. On Left panel, under Build Promotion section, click Staging Upload
	3. Upload following files:
	END

	for bj in "${BUNDLE_JARS[@]}"; do
	    echo "$bj"
	done
	;;

    * )
	### Project like tennera or openprops
	### These have only master
	release_perform
	mvn -e nexus-staging:close nexus-staging:release
	;;
esac

