#!/bin/bash
### NAME
###     zanata-pom-set-version - Set pom version
###
### SYNOPSIS
###     zanata-pom-set-version [options] <TagPrefix> <Version> <Projects>
###
### DESCRIPTION
###     This script
###         1. sets the version in pom
###         2. then commit with corresponding message.
###         3. tag the commit if version is not SNAPSHOT
###
###     Note that this script assume you are already in correct directory and
###     checkout correct branch.
###
### ARGUMENTS
###     TagPrefix
###         Prefix of the tag like 'platform-'
###
###     Version
###         Version like 4.4.0 or 4.5.0-SNAPSHOT
###         Note that final version and SNAPSHOT will have different commit message
###
###     Projects
###         Comma-delimited list of specified reactor projects, it will be passed as
###         parameter of mvn -pl
export LC_ALL=C
set -eu
ScriptDir=$(dirname $(readlink  -q -f $0))
FunctionScriptFile=${ScriptDir}/zanata-functions
source "$FunctionScriptFile"
trap exit_print_error EXIT

###
### OPTIONS
while getopts "h" opt;do
    case $opt in
###     -h: Show detail help
        h )
            zanata_script_help $0
            exit ${EXIT_OK}
            ;;
        * )
            failed ${EXIT_FATAL_INVALID_OPTIONS} "$opt"
            ;;
    esac
done
shift $((OPTIND-1))

if [[ $# -lt 2 ]]; then
    zanata_script_help_short $0
    exit ${EXIT_FATAL_INVALID_ARGUMENTS}
fi

TagPrefix=$1
Version=$2
Projects="${3-}"

if [[ $Version =~ -SNAPSHOT$ ]]; then
    SnapshotMode=1
    CommitMessage="chore(version): new snapshot version ${Version}"
    ScmTag="HEAD"
else
    SnapshotMode=0
    CommitMessage="chore(version): set version ${Version}"
    ScmTag="$TagPrefix$Version"
fi

if [[ -n $Projects && $Projects != 'null' ]]; then
    ProjectOpts="-pl $Projects"
else
    ProjectOpts=""
fi

run_command sed -i -e 's|<tag>.*</tag>|<tag>'$ScmTag'</tag>|' $(find . -name pom.xml | xargs )
run_command ./mvnw ${MAVEN_COMMON_OPTIONS:-} $ProjectOpts versions:set -DnewVersion=$Version
run_command git commit -a -m "$CommitMessage"

if [[ $SnapshotMode -eq 0 ]]; then
    ## Tag for non Snapshot version
    ReleaseNoteVersion=${Version%%-*}

    if [[ $Version = $ReleaseNoteVersion ]]; then
        ## Final version
        ## Anchor in Read the doc. version 4.4.0 become 440
        ReadTheDocAnchorVersion=$(sed -e 's/\.//g' <<<$ReleaseNoteVersion)
        TagMessage="http://docs.zanata.org/en/release/release-notes/#$ReadTheDocAnchorVersion"
        ## Tag before release, so the git description looks correct
    else
        ## Alpha, Beta, RC
        TagMessage="tag ${ScmTag}"
    fi
    run_command git tag -a -m "$TagMessage" $ScmTag
fi
